arb-dir: lib/app/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-dir: lib/app/l10n/generated
synthetic-package: false
use-deferred-loading: true
nullable-getter: false